version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: afzaalahmedkhan/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vpromemcached:
    image: memcached
    container_name: vpromemcached
    ports:
      - "11211:11211"
  
  vprorabbitmq:
    image: rabbitmq
    container_name: vprorabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: afzaalahmedkhan/vprofileapp
    container_name: vproapp
    ports:
      - '8080:8080'
    volumes:
      - vproappdata:/usr/local/tomcat/webapps


  vproweb:
    build:
      context: ./Docker-files/web
    image: afzaalahmedkhan/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
  






  